name: Azure Static Web Apps Entry

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to deploy, such as refs/tags/v1.2.3
        required: false
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy, such as refs/heads/main or refs/tags/v1.2.3
        required: false
        type: string

permissions:
  contents: read
  issues: write
  pull-requests: write
  id-token: write

jobs:
  deploy:
    name: Call Reusable Azure Deploy
    uses: ./.github/workflows/azure-deploy.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit
