name: Azure Static Web Apps Reusable Deploy

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to deploy, such as refs/tags/v1.2.3
        required: false
        type: string

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUSHROOM_040C43103 }}
          repo_token: ${{ github.token }}
          action: 'upload'
          production_branch: 'main'
          app_location: '/'
          api_location: ''
          output_location: 'dist'
          github_id_token: ${{ steps.idtoken.outputs.result }}

      - name: Notify IndexNow
        run: |
          curl --fail-with-body -sS -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d '{
              "host": "nokpizza.no",
              "key": "d4fac2f50870400e946241f1b32c4773",
              "keyLocation": "https://nokpizza.no/d4fac2f50870400e946241f1b32c4773.txt",
              "urlList": ["https://nokpizza.no/"]
            }'
